services:
  - type: web
    name: backend-chat-application
    runtime: node
    plan: free
    branch: main
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /
    autoDeployTrigger: commit
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: EMAIL_FROM
        sync: false
