services:
  - type: web
    name: backend-chat-application
    runtime: docker
    plan: free
    branch: main
    healthCheckPath: /
    autoDeployTrigger: commit
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: backend-chat-redis
          property: connectionString
      - key: CACHE_TTL_SECONDS
        value: 60
      - key: EMAIL_QUEUE_CONCURRENCY
        value: 5
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 465
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM_EMAIL
        sync: false

  - type: keyvalue
    name: backend-chat-redis
    plan: free
    ipAllowList: []
    maxmemoryPolicy: allkeys-lru
    persistenceMode: off
